# Generated by Django 5.2.2 on 2025-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(choices=[('short', 'Short-term'), ('long', 'Long-term')], max_length=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField()),
                ('sqft', models.PositiveIntegerField(verbose_name='Square footage')),
                ('amenities', models.CharField(blank=True, max_length=255)),
                ('features', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('rating', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Years of experience')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('specialties', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
