# Generated by Django 5.2.2 on 2025-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="available_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_monthly",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_nightly",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="rental_type",
            field=models.CharField(
                choices=[
                    ("short", "Short-term"),
                    ("long", "Long-term"),
                    ("both", "Both"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="sqft",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Square footage"
            ),
        ),
    ]
